Support for text-only prom endpoints who speaks http correctly + newer dd-agent (#5)
TL;DR;

Configure the prometheus check with `format: text` in case you encounter `HTTPError: 406 Client Error: Not Acceptable for url`.

PROBLEM:

The prometheus check had been trying to http-get a prom endpoint assuming it is serving PROTOBUF format,
even though it was actually serving TEXT format, which in some cases resulted in errors like:

> HTTPError: 406 Client Error: Not Acceptable for url: http://10.2.93.28:8080/metrics

More concretely, omitting the kwarg `pFormat` of `self.poll` had been resulting to the format `protobuf` rather than `text`, which results in adding an `Accept: application/vnd.google.protobuf; proto=io.prometheus.client.MetricFamily; encoding=delimited` header to your http request to a prom endpoint. A correctly implemented http server can reject the request due to mismatch between the `Accept` request header vs actual content-type of the prom metrics to be responded.

See https://prometheus.io/docs/instrumenting/exposition_formats/ for definitions of PROTOBUF and TEXT formats and corresponding Content-Type.

A real example of such correctly implemented text-only prom endpoints is one implemented with https://github.com/prometheus/client_ruby#rack-middleware.
It rejects requests w/ the above Accept header with 406 errors because the implementation specifically supports the TEXT format only.

FIX:

This change allows you to configure which format to be used specifically by PrometheusCheck, so that you can avoid the error.

You could write your config like:

```
init_config:

instances:
  - target: http://localhost:9100/metrics
    format: text
    config:
      drop:
        - .*
      keep:
        - node_cpu.*
        - node_memory.*
```

to avoid 406s in this case.